# Generated by Django 3.2 on 2022-05-11 11:35

import cuisine.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=cuisine.managers.CuisineManager.recipe_image_file_path),
        ),
    ]
